on: [pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgis/postgis:10-2.5
        env:
          # must specify password for PG Docker container image, see: https://registry.hub.docker.com/_/postgres?tab=description&page=1&name=10
          POSTGRES_PASSWORD: password
          POSTGRES_DB: nopog
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Import DB seed data
      run: psql -d postgresql://postgres@localhost/nopog -f nopog.sql
      env:
        PGPASSWORD: password
    - name: install
      run: |
        go get github.com/lib/pq
        go get github.com/stretchr/testify
    - name: lint
      run: |
        go vet .
    - name: Test
      run: go test -v -coverprofile cover.out -count 1 -failfast -race .
